name: Oops
version: ${project.version}
main: com.github.sachin.oops.Oops
api-version: 1.16
authors: [ sachingorkar ]
description: Undo your misplaced block within 2 seconds
commands:
  oops:
    description: core command for oops
    permission: oops.command.reload
permissions:
  oops.command.reload:
    description: reloads oops plugin config
    default: op
  oops.command.toggle:
    description: permission to use the toggle command
    default: true
  oops.use.undo:
    description: permission to use the undo feature
    default: true
